version: "3.9"

services:
  back:
    image: bouzalmat/back
    container_name: back
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    image: abdooch/front
    container_name: front
    ports:
      - "5173:80"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    exec: |
      'CREATE DATABASE db_aides CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
      'ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';'
      'FLUSH PRIVILEGES;'
      'EXIT;'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_aides
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
